stages:
  stage_01:
    cmd: python stage_01.py # run this command
    deps: 
      - stage_01.py # creating this itself as dependency so that if anything changes in it, will be tracked.
    outs:
      - artifacts01.txt

  stage_02: 
    cmd:  python stage_02.py
    deps:
      - artifacts01.txt
      - stage_02.py